import {getUTCTime} from './utils';

export const DEFAULT_OPTIONS = {
    carouselClass: 'carousel',
    carouselControlBackwardClass: 'carousel-control carousel-control-backward',
    carouselControlForwardClass: 'carousel-control carousel-control-forward',
    carouselControlsClass: 'carousel-controls',
    carouselDefaultBlocked: false,
    carouselDefaultSlide: 1,
    carouselHorizontalClass: 'carousel-h',
    carouselInnerClass: 'carousel-inner g-h-xs-10 g-h-lg-20 g-v-xs-10 g-v-lg-20',
    carouselSlideClass: 'carousel-slide',
    carouselTrackClass: 'carousel-track',
    carouselVerticalClass: 'carousel-v',
    containerSelector: 'body',
    emptySpaceSelector: '.j-empty-space',
    host: 'http://demo.touch-tv-front.stands.userstory.ru',
    iBBackdropClass: 'info-block-backdrop',
    iBBackdropClassFull: 'info-block-backdrop-full',
    iBBgColor: '#315efb',
    iBClass: 'info-block j-info-block',
    iBModalAttrHidden: 'hidden',
    iBModalAttrHiddenFalse: 'false',
    iBModalAttrHiddenTrue: 'true',
    iBModalCloseClass: 'info-block-modal-close',
    iBModalContentClass: 'info-block-modal-content',
    iBModalFullDescriptionClass: 'info-block-modal-full-description',
    iBModalSelector: '.j-info-block-modal',
    iBModalShortDescriptionClass: 'info-block-modal-short-description',
    iBModalTitleClass: 'info-block-modal-title',
    iBRefreshInterval: 1000,
    iBSectionAttrAmount: 'amount',
    iBSectionAttrBlocked: 'blocked',
    iBSectionAttrBlockedFalse: 'false',
    iBSectionAttrBlockedTrue: 'true',
    iBSectionAttrId: 'id',
    iBSectionAttrOrientation: 'orientation',
    iBSectionSelector: '.j-info-block-section',
    iBSelector: '.j-info-block',
    iBShortDescriptionClass: 'info-block-short-description',
    iBTitleClass: 'info-block-title',
    iBTitleClassAlign: 'info-block-title-align',
    iBTitleInnerClass: 'info-block-title-inner',
    iBWrapperClass: 'info-block-wrapper',
    layoutSelector: '.j-layout',
    time: getUTCTime(),
    videoSelector: '.j-video',
};
